#!/bin/bash

if [[ $(cat /var/www/html/VERSION) != $(wget https://raw.githubusercontent.com/ArnyminerZ/CNCPi/master/Web/VERSION -q -O -) ]]; then
    sudo git clone https://github.com/ArnyminerZ/CNCPi.git /temp/install

    sudo rm -rf /var/www/html
    sudo cp -r /temp/install/Web /var/www/html

    sudo rm -rf /temp/install
    sudo rm -rf /temp
else
    echoText="You have already downloaded the last version ("
    echoText+=$(cat /var/www/html/VERSION)
    echoText+=")."
    echo $echoText
    inGithubText="Github version: "
    inGithubText+=$(wget https://raw.githubusercontent.com/ArnyminerZ/CNCPi/master/Web/VERSION -q -O -)
    echo $inGithubText
fi